language: php
sudo: false

php:
  - '8.1'
  - hhvm # on Trusty only
  - nightly

before-install:
 - composer self-update

install:
 - composer install

before_script:
 - composer self-update
 - composer install --prefer-source --no-interaction --dev

script:
  - ./vendor/bin/psalm
  - ./vendor/bin/phpunit

